name: va-app

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    networks:
      - app-network

  LeafByte.Parking.api:
    image: va-api
    container_name: va-api-container
    depends_on:
      - mysql
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5000:80"
    networks:
      - app-network
    build:
      context: .
      dockerfile: LeafByte.Parking.API/Dockerfile

networks:
  app-network:
    driver: bridge