apiVersion: apps/v1
kind: Deployment
metadata:
  name: va-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: va-api
  template:
    metadata:
      labels:
        app: va-api
    spec:
      containers:
      - name: va-api
        image: va-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ConnectionStrings__DefaultConnection
          value: "Server=mysql;Database=testdb;User=appuser;Password=apppassword;"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"