name: .NET Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore LeafByte.Parking.sln

    - name: Build
      run: dotnet build LeafByte.Parking.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test LeafByte.Parking.sln --no-build --configuration Release --verbosity normal

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Set lowercase repo variables
      id: vars
      run: |
        echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
        echo "REPO_LC=$(echo "${GITHUB_REPOSITORY##*/}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build and push Docker image
      run: |
        docker build -f LeafByte.Parking.API/Dockerfile -t ghcr.io/${OWNER_LC}/${REPO_LC}/va-api:latest .
        docker push ghcr.io/${OWNER_LC}/${REPO_LC}/va-api:latest
      working-directory: src
